### ISSUE TITLE
Controls not working on Debian 11

### ISSUE THREAD

**Issue by Astro-Johnny** [poteresting/SpaceInvader#1]
I tried running it on terminal on Debian 11. The game seemed to run (aliens were moving around) but I seemed to be unable to perform any action.

Eventually an exception was raised:
```
Exception in thread Thread-127:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/home/janis/src/SpaceInvader/venv/lib/python3.9/site-packages/pynput/_util/__init__.py", line 210, in run
    self._run()
  File "/home/janis/src/SpaceInvader/venv/lib/python3.9/site-packages/pynput/keyboard/_xorg.py", line 545, in _run
    super(Listener, self)._run()
  File "/home/janis/src/SpaceInvader/venv/lib/python3.9/site-packages/pynput/_util/xorg.py", line 382, in _run
    self._display_stop = Xlib.display.Display()
  File "/home/janis/src/SpaceInvader/venv/lib/python3.9/site-packages/Xlib/display.py", line 89, in __init__
    self.display = _BaseDisplay(display)
  File "/home/janis/src/SpaceInvader/venv/lib/python3.9/site-packages/Xlib/display.py", line 71, in __init__
    protocol_display.Display.__init__(self, *args, **keys)
  File "/home/janis/src/SpaceInvader/venv/lib/python3.9/site-packages/Xlib/protocol/display.py", line 166, in __init__
    raise error.DisplayConnectionError(self.display_name, r.reason)
Xlib.error.DisplayConnectionError: Can't connect to display ":0": b'Maximum number of clients reached'
```

Hmm, could it be a Wayland thing? :thinking:

**Comment by poteresting** [comment]
I have run and it works on my current distro PopOS and it also worked on Ubuntu when I developed it.

In your case, it seems to me that it's not a wayland issue, it is due to many connections being made to X server that comes from infinite loop isGameRunning in the code.

A solution to this will be to close the X server display connections created with every iteration in game loop. So I have added fix in a separate branch `1-controls-not-working-on-debian-11` that might fix the issue in your case.
 
Other reason why it worked on my system and not yours could be:
 1. In your system other processes are exceeding the X server connections along with the game.
 2. Your system has less cpu core resources (i have 6 cores)
 
 Please let me know if the issue is solved. Thank you for your participation :)

**Comment by Astro-Johnny** [comment]
Thanks for the prompt response! Unfortunately 2b619cc doesn't help.

There's also runaway thread spawning. As given in the traceback in orginal post, please note `Exception in thread Thread-127`.
I think you've already given good clue where the problem is. The `with keyboard.Events() as events:` spawns a thread for connecting to X server. In this case they fill up the queue until the "Maximum number of clients reached" error occurs.

This can be an issue even when the connection to X succeeds. Since each loop iteration creates a new connection (and thread) there remains a possibility to lose keypresses during "thread handover". I suggest the event listener is only created once and used for entire runtime. Alternatlively, use of `pynput` can be re-evaluated at all, given this is a terminal program and involving X for key capture isn't strictly necessary.

**Comment by poteresting** [comment]
Thank you for your feedback! Yes I found that pynput is not the best choice here, so I removed pynput and implemented it using `curses` a terminal handling display tool. I hope that will fix the issue now in all the systems.

Let me know if the game is working now for you. Thanks

**Comment by Astro-Johnny** [comment]
Yes, the curses version now works for me on Debian. There's also no "runaway threads" anymore. :+1: 

Still, I think `curses.initscr()` should be called once and not on every loop. Consider making it's use part of the `GameState`. But since `curses` also takes over the terminal window painting, it may conflict with current board drawing functionality by `print()` calls.

I noted other bugs though. Movement right/left do not reset and the player keeps moving to end of the game field on its own. The projectiles shot by player also seem to move through the aliens without any effect. I suppose there warrant their own bug reports. :space_invader: I'm unable to verify whether the bugs appear in `pynput` version.

**Comment by poteresting** [comment]
Yes, a good point so I initialized curser in the singleton and since there are no print() in main game loop running and the board drawing happens using cursor `addstr` function, there is no conflict and it works great.

Thanks for bug report. I have fixed all bugs and the player can control their movements and projectiles do not go through the aliens, I also found couple of errors that I fixed. 

Game seems to work great now. Please checkout branch `1-controls-not-working-on-debian-11` if you wish to try it yourself. If it works well for you then I will merge those changes.

**Comment by Astro-Johnny** [comment]
Thanks! Yes, I can confirm the game is very playable now! :tada:
